DROP DATABASE IF EXISTS main;
CREATE DATABASE IF NOT EXISTS main;
USE main;

SELECT 'CREATING PRODUCT TABLE' as 'INFO';

DROP TABLE IF EXISTS products;

CREATE TABLE products (
	id INTEGER AUTO_INCREMENT ,
	make VARCHAR(30) NOT NULL,
	model VARCHAR(30) NOT NULL,
	PRIMARY KEY(id));
	
SELECT 'INSERTING DATA INTO TABLE CUSTOMERS' as 'INFO';

INSERT INTO products VALUES ( null, 'Ford', 'Focus');
INSERT INTO products VALUES ( null, 'Honda', 'Civic');
INSERT INTO products VALUES ( null, 'Ferrari', 'F70');

SELECT 'CHECKING TO SEE IF DATA INSERTED TO PRODUCT CORRECTLY' as 'INFO';

SELECT * FROM products;

SELECT * FROM products WHERE id = 1


